tws = Song.create(name: "Fell in Love With a Girl", artist: "The White Stripes", filePath: "./audio/The White Stripes.mp3", duration: 118, imagePath:'./images/tws choice.jpeg')
starSlight = Song.create(name: "Star Slight", artist: "At the Drive-In", filePath: "./audio/Star Slight.mp3", duration: 83, imagePath:'./images/star slight choice.jpg')
whenImSmall = Song.create(name: "When I'm Small", artist: "Phantogram", filePath: "./audio/When I'm Small.mp3", duration: 255, imagePath:'./images/phantogram choice.jpeg')


Score.create(name: "Jon", value: 1000000000, song_id: 1)
Score.create(name: "Bobby", value: 250000, song_id: 1)
Score.create(name: "Derek", value: 150000, song_id: 1)
Score.create(name: "Anthony", value: 200000, song_id: 1)
Score.create(name: "Felicia", value: 220000, song_id: 1)
Score.create(name: "Megatron", value: 160000, song_id: 1)
Score.create(name: "Terrence", value: 180000, song_id: 2)
Score.create(name: "Xavier", value: 820000, song_id: 2)
Score.create(name: "Patrick", value: 210000, song_id: 2)
Score.create(name: "Supertron", value: 100000, song_id: 2)
Score.create(name: "Philbert", value: 620000, song_id: 2)
Score.create(name: "Gerald", value: 210000, song_id: 2)
Score.create(name: "Stacey", value: 220000, song_id: 3)
Score.create(name: "Elizabeth", value: 190000, song_id: 3)
Score.create(name: "Gigatron", value: 340000, song_id: 3)
Score.create(name: "HIJ", value: 320000, song_id: 3)
Score.create(name: "Gertrude", value: 430000, song_id: 3)
Score.create(name: "Ric", value: 1000000000, song_id: 3)
